# For Github User
# github_username: "slack_member_id"

github_username_A: "D07KAP8K9L6"
# github_username_B: "slack_member_id_B"
# github_username_C: "slack_member_id_C"
# Laurenfrost: "XXXXXXXXX"

# For Github Team
# github_teamname: "slack_member_id"

# github_teamname_A: "slack_member_id_D"
